version: '3.3'

services:
  client:
    build:
      context: .
      dockerfile: Dockerfile
    image: housing-anywhere
    container_name: housing-anywhere
    volumes:
      - ./src:/app/src
    ports:
      - 3000:3000